name: Main

on: push

jobs:
  test_publish:
    name: Test and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Publish (dry run)
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }} # Only dry-run if not a release.
        run: cargo publish --dry-run

      - name: Publish
        if: startsWith(github.ref, 'refs/tags/') # Only publish for new release.
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: make publish
